name: Main

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.2'

      - name: Check Go version
        run: go version

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: jetbrains
          BINDIR: bin
        run: |
          sudo apt update && sudo apt install -y upx-ucl
          upx -V
          make -j releases

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          draft: false

      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.repository.default_branch }}'

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Generate Readme
        run: |
          go build -o bin/jetbrains -gcflags="all=-N -l" -ldflags '-X "github.com/designinlife/jetbrains/common.Version=${{ steps.previoustag.outputs.tag }}" -w -s -extldflags="static"' .
          ./bin/jetbrains ls --readme >README.md
          cat README.md

      - name: Commit Readme
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          message: 'Update README.md'
          add: 'README.md'
