name: Main

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'

      - name: Check Go version
        run: go version

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: jetbrains
          BINDIR: bin
        run: make -j releases

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            bin/*linux-amd64*
            bin/*windows-amd64*
          args: -fq

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          draft: false
