# .github/workflows/release.yaml

name: Go Release Binaries

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "1.20.8"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: -s -w
