# .github/workflows/release.yaml

name: Go Release Binaries

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S') >> ${GITHUB_ENV}

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "1.21.1"
        # executable_compression: upx
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: -X 'github.com/designinlife/jetbrains/common.Version=${{ github.event.release.tag_name }}' -X 'github.com/designinlife/jetbrains/common.BuiltOn=${{ env.BUILD_TIME }}' -s -w -extldflags='static'
